### ISSUE TITLE
Updating model generates wrong SQL Query

### ISSUE THREAD

**Issue by anka** [koss-lebedev/active_dynamic#10]
I am using `activerecord (5.1.4)` and `active_dynamic (0.5.8)` and suddenly when updating/saving my model I get the following error:

```
ActiveRecord::StatementInvalid: PG::UndefinedTable: ERROR:  missing FROM-clause entry for table "attribute"
LINE 1: ..._dynamic_attributes"."customizable_type" = $2 AND "attribute...
                                                             ^
: SELECT  "active_dynamic_attributes".* FROM "active_dynamic_attributes" WHERE "active_dynamic_attributes"."customizable_id" = $1 AND "active_dynamic_attributes"."customizable_type" = $2 AND "attribute"."id" = $3 AND "attribute"."customizable_id" = $4 AND "attribute"."customizable_type" = $5 AND "attribute"."name" = $6 AND "attribute"."display_name" = $7 AND "attribute"."datatype" = $8 AND "attribute"."value" = $9 AND "attribute"."required" = $10 AND "attribute"."created_at" = $11 AND "attribute"."updated_at" = $12 LIMIT $13
```

As you can see, within the query it uses the table alias `attribute` instead of `active_dynamic_attributes`. The error does not appear on new records only on existing ones.

**Comment by koss-lebedev** [comment]
Can you provide an example of your model with`has_dynamic_attributes` and what query you're running?

**Comment by anka** [comment]
I did not run any query on my own but after updating a model which already has a dynamic attribute (including a value) this exception (and wrong sql statement) arises within my application. 

I am using a custom class as attribute provider like this

```
class DeviceAttributeProvider

  def initialize(model)
    @device = model
  end

  def call
    DeviceAttribute.all.map do |attr|
      ActiveDynamic::AttributeDefinition.new(
          attr.display_name,
          system_name: attr.name,
          datatype: attr.datatype,
          required: attr.required?
      )
    end
  end

end
```

Everything else looks the same like the example application of this gem. Currently I am using the gem version `0.5.8`.

**Comment by koss-lebedev** [comment]
I don't seem to be able to recreate this issue. I've added this test case: https://github.com/koss-lebedev/active_dynamic/blob/6eb50c0a83100d71870d1a93a909203a1b2a9511/test/active_dynamic_test.rb#L73. Could you take a look and tell if it accurately represents your case?

**Comment by koss-lebedev** [comment]
OK, I'm closing this to inactivity.
