### ISSUE TITLE
Assigning `nil` to existing dynamic attributes does not persist to the database

### ISSUE THREAD

**Issue by singjsong** [koss-lebedev/active_dynamic#11]
For some reason, assigning a dynamic field to `nil` when it has already been previously set does not work. It will persist a blank String (`''`) to the `active_dynamic_attributes` record, but not `nil`.

**Comment by singjsong** [comment]
Nvm, I found where it's doing this on `/lib/active_dynamic/has_dynamic_attributes.rb:89`:
```ruby
_custom_fields[field.name] = value.to_s.strip if value
```
Not a big fan of that. Any particular reason why it was done like this?

**Comment by koss-lebedev** [comment]
That's a good question. I think the original intent was to always cast values to strings because they are stored in a char column in DB, but `nil` values should definitely be allowed. I'll fix this problem tomorrow. Thanks for reporting!

**Comment by koss-lebedev** [comment]
Resolved in `0.5.9`
