### ISSUE TITLE
General questions

### ISSUE THREAD

**Issue by Svashta** [koss-lebedev/active_dynamic#2]
Hello Koss,

sorry for opening an issue, I was actually looking for a private channel to contact you, but couldn't find any :). I've stumbled upon your gem while searching for dynamic attributes solutions in Rails. Your solution really looks promising, but i do have few questions as I am still learning ruby and am a bit confused.

- do i understand correctly only one model can have dynamic attributes? From gem code i can't see a way to define multiple models which carry dynamic attribute definitions (config.provider_class)?
- would it be possible to add Boolean values?
- is it possible to search by these attributes?

What I would actually like to achieve is to have an Asset model with dynamic attributes - but these attributes would be defined based on Asset Category. So, in my case I would actually need to define additional attributes for the Asset on Asset Category. Would that be possible?

I see the repo is active, so I am really considering giving it a try, but need to clarify these problems I could have in the future. If you know of any better solution to what I would like to achieve, I would really appreciate any advice.

Thanks for your help,
Mitja

**Comment by koss-lebedev** [comment]
Hey @Svashta ,

I'm happy to help. So regarding your questions:

- you can have as many models with dynamic attributes as you want. You're right that there's only one provider_class, but it can be used to resolve dynamic attributes for multiple models. I added an example to README showing how it works
- You're not required to use built-in `ActiveDynamic::DataType` enumeration. In fact, I'm planning to remove it from the library in the nearest future, so I would encourage you to use your own. You can create an enumeration with any data types that you want to support (booleans included). Just make sure that enumeration values should be integers because they are stored in integer column in DB
- I haven't tried that, but generally speaking, I think it is. You can write a query to join your own tables with ActiveDynamic table, and then use standard SQL queries. If you decide to give it a try, let me know if you run into any issues.

**Comment by Svashta** [comment]
Looks promising! :) Thanks for the updated Readme, I have a better understanding now.
Some further questions:

- if there are multiple models, and as i understand all dynamic attributes and values are going into the same DB table - are there any performance considerations? I guess if there are 10 models, this table could potentially grow in size pretty fast.
- i am trying to picture how to create dynamic attributes definitions on category, but use them on asset. Do you have any idea on that? Can't really picture it at the moment.
- for searching i am already considering to maybe do it via elasticsearch - but this is not so important right now, i am sure there is some elegant way to do it :)

Thanks for all the answers. I am definitely going to try it with help of this gem. I think it is really close to what i need to achieve and would be of great help.

**Comment by koss-lebedev** [comment]
- Yeah, you're right that all the values go into a single DB table, but so far I haven't experienced any performance issues. There are DB indices on both model type and model id columns, so retrieval time for DB records is proportional to the number of rows belonging to a specific model, not to the total number of rows in the table.
- you can take a look at this example project (https://github.com/koss-lebedev/active_dynamic_demo); basically, it uses ContactAttribute model to store attribute definitions and then uses them on Contact model, I think it's pretty close to what you're trying to achieve

**Comment by Svashta** [comment]
Hey, sorry to bother you again.
I've come pretty far i guess as basic things are working perfectly.
This is what i have so far (simplified):

```ruby
#Asset
has_dynamic_attributes
belongs_to :asset_category
```
```ruby
#AssetCategory
has_many :assets
has_many :asset_attributes
```
```ruby
#AssetAttribute
belongs_to :asset_category
```

```ruby
#Provider
...
def call
    if @model_class == Asset
      AssetAttribute.all.map do |field|
        ActiveDynamic::AttributeDefinition.new(
          field.name,
          datatype: field.datatype,
          required: field.required?)
      end
    else
      []
    end
  end
...
```

I can create AssetAttributes, which belong to some specific AssetCategory.
Now, the problem is, as far as i see i can only assign these Attributes to any Asset.
What I would need is a way to somehow pass the category to the call and be able to select only those attributes which are necessary for specific category. I don't think this is currently possible.

I see few options:

- to extend initialize parameter to pass in *args and simply use whatever i would need (this i think would be best solution)
- to simply call all the attributes and then hide or reject or something the ones i don't need in view and in params (here i suspect i would be having problems with attributes that are set as require) - feels messy

What do you think, did I over complicated things.
I know one other option (STI) and different classes for categories, but i need users to define categories, they are not to be predefined.

I hope you see where I'm stuck :). Thanks for any input.

**Comment by koss-lebedev** [comment]
That's an interesting question.

I figured that the best way to handle this is to pass the actual instance of the model to the constructor of Provider, not just model class. This way,  we can access properties of the model within `call` method, so in your case, you would be able to get `AssetCategory` off of `Asset` instance.

You can give it a try, just install the gem from the Github source:

`gem 'active_dynamic, github: 'koss-lebedev/active_dynamic'`

and update the logic in your provider class since now it will receive the actual `Asset` instance.

**Comment by Svashta** [comment]
This is perfect! I already had a little bit different solution, where I did a select on AttributeDeffinitions array for asset_category I needed, but this is now better as I can do it directly in the Provider. Its much cleaner and useful.

I have everything set now and things work really well!
I do have one more "problem" where you could maybe help me a bit more.

You have a predefined set of attributes on AttributeDefinition (:display_name, :name, :datatype, :value).
Now, in my AssetAttributes I have a little bit more information that can be set, like description and placeholder (for simple_form hint and placeholder values.). Eventually, there could be more on other types of dynamic attributes.

I solved the problem by monkey patching your AttributeDefinition class like so:

```ruby
AttributeDefinition.class_eval do

    attr_reader :display_name, :name, :datatype, :value, :asset_category, :description, :placeholder

    def initialize(display_name, options = {})
      @display_name = display_name
      @name = options[:system_name] || display_name.parameterize.underscore
      @datatype = options[:datatype]
      @value = options[:default_value]
      @required = options[:required]
      @asset_category = options[:asset_category]
      @description = options[:description]
      @placeholder = options[:placeholder]
    end

    def required?
      !!@required
    end

  end
```

It works perfectly and i can use those values on my form just fine.
The problem is, while i am developing and testing it, when something goes wrong i get an error like this:

`ArgumentError - A copy of DynamicAttributesProvider has been removed from the module tree but is still active!`

And any further requests are not working anymore until I restart the application.
As I said, I am still learning, and I can't say for sure is this because of monkey patching your class or general problem (i guess it is my monkey patching causing this because it is only evaluated once as it is in initializer, and when something goes wrong this class is than broken or something).

Anyway, things work, but I would like to know whether it is possible to do this (additional AttributeDefinition attributes) without monkey patching? I don't need to save those value to your table in the DB as they are only for form view purposes, but still , i need to access them somehow.

Otherwise, I am really happy how things are progressing and I am really gratefull for this nice gem!

**Comment by Svashta** [comment]
I see now I have troubles with my own AttributeDefinition attributes :)
So far I have been focused on getting things work in basic terms - like form display and create records.
While this is perfectly OK, persisted records (edit form) is a different story. Now It doesn't go through provider it just selects from active_dynamic_attributes and of course:

- there is currently no way to know which attributes are for current asset category
- i can't display edit form because description/placeholder is not saved and as it doesn't go through Provider i can't get to the value

Any hints? :)

**Comment by Svashta** [comment]
Hey, another day another me :)

I've solved the problem with "A copy of DynamicAttributesProvider ...". It wasn't monkey patching, nor gem code. It was a way I was calling AssetAttribute inside Provider. I had to change it to ::AssetAttribute. Solved.

I have also progressed with my custom attributes, which are now saved into the table, so i can access them on edit form.And speaking of editing...

- currently you retrieve all attributes for saved object from the table. Which is fine , except when object was saved and additional dynamic attributes are defined later. Then, this object is not aware of new attributes? I am looking for a way to combine saved attributes and those from Provider. But no luck so far. This, I think, should be somehow possible,
- how do i save "required" value with the object? Currently, although everything is fine on New object form, when it is actually saved, required value is always false. I don't see anything related to that in demo project. I am wondering how to save it with the attribute.

I very far to what I want and this is of great help. Just some more polishing :)

I would also suggest that you include dependant: :destroy to has_many definition as there is probably no reason to keep model associated attributes in the table.

BR

**Comment by koss-lebedev** [comment]
I see what you mean. I think it will be a quite common use case to have dynamic attributes loaded from the provider all the time, not only for new records, so the configurable option would be fine.
I added `resolve_persisted_proc` option that works kind of like provider class - it will be passed a model and it has to return `true` if you want your saved records to resolve dynamic attributes from the provider or `false` to resolve attributes from DB:

```ruby
ActiveDynamic.configure do |config|
    config.provider_class = ProfileAttributeProvider
    config.resolve_persisted_proc = Proc.new { |model| false }
end
```

So far I've tested only that this change doesn't break any of existing functionality, but I still need to rewrite specs to include tests for new logic. Feel free to add details here if you run into any issues.

Also, I don't like the name `resolve_persisted_proc`, it's not very descriptive. Maybe you have a better suggestion?

**Comment by Svashta** [comment]
Hey, thanks for helping me out.
It seems like ActiveDynamic.configuration.resolve_persisted_proc.call(self) always returns False, so it always goes to resolve_from_db. I've tried to go directly with resolve_combined, but i am getting `undefined method `<<' for #<ActiveRecord::AssociationRelation []>`.

While we are at solving problems, i've found another one, which I was already suspecting at the beginning and i've already tried to bypass it, but with no success.
Currently a set of required attributes is always set from all defined attributes, not just ones defined for current object. This is related to my categories definitions. I did manage to narrow down permited params attributes to only ones defined for object AssetCategory, but because required ones are included from all the attributes defined, it doesn't allow me to save object as validation fails.

I think this is because how validation is being built inside HasDynamicAttributes. It should be somehow narrowed down to only those that are defined for current dynamic_attributes.

BR!

**Comment by koss-lebedev** [comment]
OK, thanks for the feedback! I definitely will be working on these issues at the end of the week, but if you don't want to wait for me, you are welcome to join the development. As you've probably noticed, the code base is quite simple and almost all relevant code is inside HasDynamicAttributes module, so feel free to contribute

**Comment by Svashta** [comment]
Yeah, I am banging my head currently how to combine dynamic attributes for persisted objects. Seems like an impossible task. as we can't just simply add to AssociationRelation. Seems like it is only possible with joins... I will see how it goes, but am really worried it simply can't be done this way.

Thx!

**Comment by prasadpilla** [comment]
Hey @koss-lebedev, 

First things first, Thanks so much for building this one. Just love it, the API looks very flexible and extensible.

I have couple of questions,

1. Can we use these dynamic attributes in ActiveRecord queries ex: User.where(dynamic_attr1: 'value')

**Comment by koss-lebedev** [comment]
hey @prasadpilla ,

thank you for kind words! To answer your questions:

1) At this time there isn't. I'm thinking that we could add `where_dynamic` method instead of messing with the default `where` method, but I'm still struggling with the implementation.

2) It should. If something doesn't work, you can create a new issue and include the code snippet that you're using, and I'll try to help you with it.

**Comment by prasadpilla** [comment]
@koss-lebedev,

Thanks for the quick response.

#1 Yes, where_dynamic makes sense. I would like to contribute to this feature, let me know if there is a channel where i can reach you to discuss.
#2 yes sure, I'll try again to make sure I am doing everything right and create an issue if it doesn't work.
