### ISSUE TITLE
Any plans for ActiveRecord >= 5.1 support?

### ISSUE THREAD

**Issue by brendancf** [koss-lebedev/active_dynamic#5]
I'm using Rails 5.1.1 and wanted to give this gem a try.  Thanks

**Comment by koss-lebedev** [comment]
hey @brendancf ,

It should work with 5.1.1 without any issues. This gem relies only on `has_many` and `before_save` methods from ActiveRecord, which I believe didn't change. I updated gem dependency requirement to allow for newer AR version.

Let me know if you run into any issues

**Comment by brendancf** [comment]
thanks. I did fork it yesterday to change the gemspec so that it would allow installing with rails 5.1.  I did just work. I had to make one other small change to quiet a deprecation warning.
