### ISSUE TITLE
Adding runtime scope to attribute provider

### ISSUE THREAD

**Issue by jasonpaluck** [koss-lebedev/active_dynamic#7]
Thanks for all your work on this project! I have a multi-tenant app where scopes govern access to organization (customer)-specific data. This means each organization can define their own dynamic attributes to be applied only to their users. Since the UserAttributeProvider class doesn't have access to the `current_user` or `current_organization` helper methods, any thoughts on how I can pass those into the call method so I can keep the attributes from bleeding across organization?

Where you use a strategy such as: 

`UserAttribute.all.map do |field|` ...

I need to append a class method such as:

`UserAttribute.for_organization(current_organization).map do |field|` ...

Thanks!

**Comment by Svashta** [comment]
Hi,

i, too, have multi-tenant application and am using this gem successfully.
First of all it depends, probably, how your multitenancy is designed, and second, UserAttribute should belong to User, which i guess, is already per-tenant, so i don't see much problem there?

**Comment by jasonpaluck** [comment]
Thanks for the quick response! User attributes belong to an organization, which is to say that I allow organization admins to define the attributes for all users in their organization at once. In order to fetch the user attributes for any given user, I need to pass in the `current_organization`, as in:

`UserAttribute.for_organization(current_organization)`

Since your setup has this call being made in an initializer, I don't have any way to pass in the `current_organization` context and I can only get the unscoped list of attributes (i.e. all attributes for all customers) rather than just those for the current organization.

**Comment by koss-lebedev** [comment]
Hey @jasonpaluck ,

it's hard to say how it'd work in your particular case, but the way I'd approach it is to have an attribute accessor `current_organization` on the model that has dynamic attributes, so than you'd have access to it in the initializer. Dynamic attributes are lazily loaded, so if you are able to set `current_organization` property on your model __before__ accessing dynamic attributes, that should work.

**Comment by jasonpaluck** [comment]
Thanks, I'll give it a shot and report back here in case anyone else runs into the same issue.

**Comment by Litty203** [comment]
Facing the same problem, how to access attr_accessor variable in AttributeProvider class? 
Please help

**Comment by koss-lebedev** [comment]
`AttributeProvider` receives an original model in its constructor, so you can call your attr_accessor variable as `@model.your_attribute`
