### ISSUE TITLE
Deprecation Warning for Rails 5.2 and passing class name not as string

### ISSUE THREAD

**Issue by anka** [koss-lebedev/active_dynamic#8]
Using version `0.5.2`

DEPRECATION WARNING: Passing a class to the `class_name` is deprecated and will raise an ArgumentError in Rails 5.2. It eagerloads more classes than necessary and potentially creates circular dependencies. Please pass the class name as a string: `has_many :active_dynamic_attributes, class_name: 'ActiveDynamic::Attribute'`

**Comment by koss-lebedev** [comment]
Thank you for the details! This warning is fixed in version `0.5.8`
